### ISSUE TITLE
src files and icon sprites missing

### ISSUE THREAD

**Issue by nickberens360** [themesberg/windows-95-ui-kit#4]
First of all, this is amazing! One question though. On your page [here](https://themesberg.com/product/ui-kit/windows-95-ui-kit) under folder structure there is a src dir and also a gulpfile but I am not seeing either when I cloned the repo. Also in the pixel.css there a sprite asset `w95-icons-sprite.png` that is missing.  Just wondering if I am in the correct repo?

Thanks, Nick

**Comment by zoltanszogyenyi** [comment]
Hey @nickberens360,

Thanks! Those sprites were the old original W95 icons, but because of copyright issues, we could not continue to use them :(

We use emoticons now.

**Comment by nickberens360** [comment]
@zoltanszogyenyi gotcha, the emojis give the same vibe. It's been fun to work with! I'm making a nuxt app for my agency to celebrate our 25th anniversary. Thanks for a great starting point!
https://60ba6d44d3e9290008d8b61d--wisnet96.netlify.app/
